name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        node-version: '20'
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.9
    - name: Install dependencies
      run: |
        pip install -r requirements.txt
    - name: Run tests
      run: |
        pytest tests/
    - name: Build Docker image
      run: |
        docker build -t bow-model .
    - name: Push Docker image
      run: |
        docker tag bow-model <fasghar40>/bow-model
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push <fasghar40>/bow-model